version: '3'

services:
  go:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: web101-server
    container_name: web101-server
    volumes:
      - "./server/data:/go/src/web101/data"
    networks:
      - web101
    depends_on:
      - web101-mongo

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: web101-nginx
    container_name: web101-nginx
    ports:
      - 80:80
    networks:
      - web101

  web101-mongo:
    image: mongo
    container_name: web101-mongo
    ports:
      - 27027:27017
    volumes:
      - web101-data:/data/db
    networks:
      - web101

volumes:
  web101-data:

networks:
  web101:
    driver: bridge