version: '3'

services:
  go:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: web101-server
    container_name: web101-server
    volumes:
      - "./server/data:/app/data"
    networks:
      - web101
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: web101-nginx
    container_name: web101-nginx
    ports:
      - 80:80
    networks:
      - web101

networks:
  web101:
    driver: bridge