version: '3'

services:
  go:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: web101-server
    container_name: web101-server
    volumes:
      - "./server/data:/go/src/web101/data"
    networks:
      - web101
    extra_hosts:
      - "local:192.168.64.1"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: web101-nginx
    container_name: web101-nginx
    ports:
      - 80:80
    networks:
      - web101

networks:
  web101:
    driver: bridge